name: chat_ui
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  http: ^0.13.5
  riverpod_annotation: ^2.0.2
  uuid: ^3.0.7
  go_router: ^6.5.1
  intl: ^0.18.0
  extended_text_field: ^11.0.1
  bot_toast: ^4.0.3
  async: ^2.10.0
  flutter_slidable: ^2.0.0
  darq: ^1.2.1
  extended_list: ^3.0.0
  flutter_slider_drawer: ^2.1.3
  flutter_markdown: ^0.6.14
  extended_text: ^10.0.1
  nil: ^1.1.1
  url_strategy: ^0.2.0
  mmkv: ^1.2.16
  shared_preferences: ^2.1.0
  showcaseview: ^2.0.3
  extended_image: ^7.0.2
  audioplayers: ^4.0.1
  record: ^4.4.4
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4
  icons_launcher: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/files/

icons_launcher:
  image_path: "assets/logo/logo.png"
  platforms:
    android:
      enable: true
    web:
      enable: true
    windows:
      enable: true
