name: chat_ui
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  http: ^0.13.5
  riverpod_annotation: ^2.0.2
  uuid: ^3.0.7
  go_router: ^6.5.1
  intl: ^0.18.0
  extended_text_field: ^11.0.1
  bot_toast: ^4.0.3
  async: ^2.10.0
  flutter_slidable: ^2.0.0
  darq: ^1.2.1
  extended_list: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/files/

